### ISSUE TITLE
Is there a reason for discarding app1 in Alibaba traces after the clustering?

### ISSUE THREAD

**Issue by kapilagrawal95** [mSvcBench/muBench#11]
Hi, I was running this Matlab code to get Alibaba’s application dependency graphs at a large scale with ~20 files combined. I observed a peculiar behavior that typically the first cluster outputted by spectral clustering was very large in comparison with others. On going through your code, I realized that you log the call graphs as json only starting the 2nd app. Is there a reason for doing this such as the first application is too noisy or is it just to save the time and memory by not logging it?

**Comment by andreadetti** [comment]
app1 seems to be a global api-gateway for all applications. So we discarded it to reconstruct the graph of different applications.
