### ISSUE TITLE
Container monitoring-install.sh File Kiali.yaml spelling error

### ISSUE THREAD

**Issue by parthokunda** [mSvcBench/muBench#14]
I followed the manual to install muBench on minikube. ```sh ./monitoring-install.sh``` command was giving me an error at the end like 
```error: the path "kilai.yaml" does not exist
error: the path "kilai-nodeport.yaml" does not exist
```
I have added the last few lines of that file as an image. ```kilai``` should be ```kiali```
![image](https://github.com/mSvcBench/muBench/assets/76593389/e7958e51-7207-4433-8679-faabb39c0724)
Repo's file seems to be fine. Container image needs to be updated.

**Comment by MingCHEN-Github** [comment]
Hi Bro, i also found this issue and fixed it last week, I am wondering have you successfully deployed this muBench to the cluster? 
For me, I can use minikube to deploy muBench and get some metrics data, but I still cannot deploy muBench into the cluster with multiple nodes. I tried k8s cluster and microK8s cluster, similar issue like the following figure (always showing several microvervices that are deployed to the working nodes are having proxying issues). Probably comes from the **istio/proxy2:1.18** image and **msvcbench/microservice_v4-screen** image.  I'm still checking the logs, pod yaml files, etc.
![image](https://github.com/mSvcBench/muBench/assets/5981694/83525ae4-ecf5-43e7-8d59-d85489eb0b73)

**Comment by parthokunda** [comment]
Sorry for the late reply. No, I am also facing the same issue on the cluster. Running the command ```python3 Deployers/K8sDeployer/RunK8sDeployer.py -c Configs/K8sParameters.json``` generates request timeout. Let me know if you have any solutions.
Also, on Minikube it is working fine for example ```Processed request 2810, latency 834, pending requests 3```. But following the manual, [the given type](https://github.com/mSvcBench/muBench/blob/main/Monitoring/kubernetes-full-monitoring/muBenchMonitors.png) of output is not coming up for me.
My Grafana Output: 
![image](https://github.com/mSvcBench/muBench/assets/76593389/a605506b-56fc-4474-9e93-2b2699761fa8)
Kiali Output: 
![image](https://github.com/mSvcBench/muBench/assets/76593389/8a55778d-78fa-4e53-9115-5e302513a958)
Istion-ingress showing this error.
![image](https://github.com/mSvcBench/muBench/assets/76593389/b370803f-dd95-48d1-bdf1-b1d25132fcd0)
Can you please let me know if you have the same issue or how you fixed it?

**Comment by MingCHEN-Github** [comment]
Hello @piratepartho 

Currently, I am a bit busy. Sorry for the late reply.

Overall, I still have some issues regarding this Benchmark when deploying it across a multiple-node k8s cluster.
The following tips are based on my experiences and you may have a look for your reference. 

(1) Before you run 

> python3 Deployers/K8sDeployer/RunK8sDeployer.py -c Configs/K8sParameters.json

, please make sure all your pods and the containers in each pod are running and ready; This command is basically for generating requests to the muBench microservice pods.



(2) for the _istio-ingress_ pod, you may need to change the ip of  "_ms_access_gateway": "http://192.168.49.2:31113"_, in 

> muBenchConfigs/RunnerParameters.json

 according to your own deployed cluster;


(3)  if you deploy your cluster in the private cloud/VM environment (not in a public cloud vendor, like Google K8s, Azure k8s etc.), you need to change the service type from _LoadBalancer_ to to _NodePort_ , which you can refer to the 90th  line in the following screenshot.

![image](https://github.com/mSvcBench/muBench/assets/5981694/84caf37e-f24b-4637-a240-a8342ba8c053)

Or you can change the service type before you install istio, you can change the values.yaml file used by helm in the 57th line code of https://github.com/istio/istio/blob/master/manifests/charts/gateways/istio-ingress/values.yaml

Or change the default.yaml profile if you install istio by istioctl command at the 168th code line at https://github.com/istio/istio/blob/master/manifests/profiles/default.yaml  

(4) Even though some microservice pods/containers are not ready (which means the muBench is not fully running), we still can get some metrics data, as shown in the following pictures:
![image](https://github.com/mSvcBench/muBench/assets/5981694/11a7aa2e-643e-457b-ae73-f4340f269828)
![image](https://github.com/mSvcBench/muBench/assets/5981694/71f51448-85df-422b-94c2-5570a8951765)

If you just wanna every component of muBench running smoothly and don't need much deep research on this topic, you can hard-code the microservice s0~s9 to be running the master node.  Then everything pod includes muBench and monitoring platforms will be running smoothly.


(5) When deployed across multiple nodes in a private k8s environment,  I think the issues with muBench probably come from the communications between the data plane and the control plane. Now, I am reading the source code of istio https://github.com/istio/istio/tree/master and trying to find some possible workarounds.

**Comment by andreadetti** [comment]
Hi, we updated the Docker image. We do not have problem with istio. For problems with muBench microrservices, please edit Configs/K8sParameters.json if your Kubernetes dns-resolver service is different from kube-dns. For instance, for some clusters it is named coredns. Otherwise, nginx pod gets error status. In our case muBench is perfectly wotking on a Kubernetes cluster with many nodes. The cluster has been made with kubeadm or kubespay.
