### ISSUE TITLE
Connection issues muBench container and Minikube

### ISSUE THREAD

**Issue by wmeijer221** [mSvcBench/muBench#15]
When following the installation guide for muBench I ran into some trouble connecting the container with my Minikube cluster (both of which are running on the same device). By default, my firewall dropped any packets coming from Docker's networking interface going to Minikube's because of an awkward interaction of the rules listed in the different "Docker isolation stages" (I didn't know how this worked, but found [this post](https://unix.stackexchange.com/questions/744884/understanding-packet-flow-through-iptables-rules-for-docker-container-bridge-net#:~:text=The%20DOCKER%2DISOLATION%2DSTAGE%2D1%20chain%20has%20two%20rules,e.g.%2C%20FORWARD%20or%20INPUT) quite insightful). 

Anyways, I ended up adding two additional rules to my firewall after which it worked, and figured others might benefit from this information at some point in the future. Simply put, I allowed packets to be sent between the muBench container to the Minikube cluster.

If you're trying this solution, the IP addresses and the name of Minikube's networking interface are likely different. You can find Minikube's internal IP using ``kubectl describe node minikube | grep InternalIP``, and muBench's using ``docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mubench`` (thanks, [this person](https://stackoverflow.com/questions/17157721/how-to-get-a-docker-containers-ip-address-from-the-host)). Figuring out the networking interface used by Minikube is a bit more of a hassle. I ended up starting a shell on the Minikube node using [kubectl-node-shell](https://github.com/kvaps/kubectl-node-shell) where I started continuously pinging ``google.com``, and simultaneously logged all network activity using [Wireshark](https://www.wireshark.org/). Eventually, it will become clear which one it uses.

```bash
sudo iptables -I DOCKER-ISOLATION-STAGE-1 1 -p all -j RETURN -i docker0 -o br-ad10b0febf7c -s 172.17.0.3 -d 192.168.49.2
sudo iptables -I DOCKER-ISOLATION-STAGE-1 1 -p all -j RETURN -i br-ad10b0febf7c -o docker0 -s 192.168.49.2 -d 172.17.0.3
sudo iptables-save
```

After this, it worked like a charm! Good job devs! :D

**Comment by andreadetti** [comment]
Great
