### ISSUE TITLE
difference between request processed in Runner.py with traces shows in Jeager Ui

### ISSUE THREAD

**Issue by hassanSattariNia** [mSvcBench/muBench#18]
i try run Runner.py with 1000 event workload and run success like this picture:
![image](https://github.com/mSvcBench/muBench/assets/85049488/22d50da6-9879-4b78-a97d-03271f4f5c05)
but when i try see this request and result as json file include traces of my request

i just see 24 request trace ,
and this  is  large difference between them  (1000 && 24):
![image](https://github.com/mSvcBench/muBench/assets/85049488/0d8bcf67-11fc-437c-a06a-8e662bcd628f)

can any body tell me about difference of these numbers?

**Comment by andreadetti** [comment]
Jaeger does not track all requests, so you see 24 instead of 100. To see spam, check related boxes.

**Comment by hassanSattariNia** [comment]
in top problem i execute 1000 request and jeager just record 24 request.
i checked monitoring config and i find out in this project ,  for monitoring used  istio .
istio have default rate sample 1% with this environment variable PILOT_TRACE_SAMPLING .
i solve my problem with change  monitoing-install.sh with bottom command
helm install istiod istio/istiod -n istio-system --wait --set pilot.traceSampling=100 .

whats your idea about my work i do it ?
is it correct way ?

**Comment by andreadetti** [comment]
It sounds good
