### ISSUE TITLE
Stress network IO when calling external_services

### ISSUE THREAD

**Issue by paprikaw** [mSvcBench/muBench#23]
Hi teams,

I wonder if it is possilble to stress IO when a service cell call external services. For example, a service cell may be able to generate dummy bytes and send to external services. This pattern is usally seen in the IoT scenario or any cases when microservices need uploading streaming datas to other microserivces.

Is this possible with the current implementation of muBench?

**Comment by andreadetti** [comment]
Hi, currently no. A µbench microservice can only get the data from an external service but not do the push.
