### ISSUE TITLE
How to handle "(?)" or "." in Alibaba Call Graphs

### ISSUE THREAD

**Issue by kapilagrawal95** [mSvcBench/muBench#5]
Hi,

This post of mine (https://github.com/alibaba/clusterdata/issues/175) led me here. I am working with these call traces and my use-case includes looking at these call graphs for some downstream cluster management task. I am parsing these call graphs into a graph library called NetworkX (python) but I am not sure whether I should treat "(?)" or "." as a unique service. For all we know, these are missing values that could be referring to any of the remaining services. If this is the case, then what should my approach be to generate the right set of call graphs? For once, I considered dropping all the call graphs (CG) which have even a single occurrence of these strings but turns out I lost quite a lot doing this. For example, in CG_0, there were ~130k traces that got reduced to ~7k (correct me if I am wrong here) when I ignored those strings. Any advise will be appreciated?

Thanks,
Kapil

**Comment by andreadetti** [comment]
Please have a look at [trace_sanity](https://github.com/mSvcBench/muBench/blob/main/examples/Alibaba/Matlab/trace_sanity.m) algorithm.
Anyway, yes, we removed many many incomplete traces that have "(?)" or “." . 
The only patch we implemented is that when the rpcid == 0.1 and the id of the upper microservice is equal to (?) then we assume that the upper microservice is the application gateway (entry_point) and therefore we do not trashed the trace. For the other cases for which the resulting graph is found to be unconnected, we trashed the trace.
