### ISSUE TITLE
Alibaba Example

### ISSUE THREAD

**Issue by kapilagrawal95** [mSvcBench/muBench#6]
Hi,

First off, kudos to you and your team for putting together such a nice benchmarking suite. I appreciate it! 

I was toying around with your code specifically the Alibaba portion. I looked at how you have compiled each call graph as a trace in a traces-mbench.zip folder. I had a couple of questions regarding this processed traces that you have put together. I'll ask my questions with this running example (in folder par/app2/trace00003.json):

{
    "s0__79818": [
        {
            "s17__57006": [
                {}
            ]
        },
        {
            "s28__69309": [
                {}
            ]
        },
        {
            "s18__58478": [
                {
                    "s18__60776": [
                        {
                            "s2__55751": [
                                {}
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

The way I am interpreting this json is service s0 calls s17, s28, and s18. s17 and s28 do not call any other service whereas s18 calls two services: s18 and s2. Note that here s18 is calling s18 which I am interpreting is a sub-service of s18. Is my understanding correct? I wanted to find out what these numerics are that follow "__". Do these refer to the count of how many times a service is called? Or is it just some arbitrary numeric id that you assign? 

**Edit: On carefully reading your code, it looks like you are randomly generating an int from 1 to 10^5 to get numeric.**

**Comment by kapilagrawal95** [comment]
Are these traces looking at only RPC calls?  If so, how can a service (s18 in the above case) call itself? Is a service calling itself a common phenomenon in practical settings? If yes, how do they communicate? Is it that a service has two pods (assuming a k8 cluster) and one of the pods of the service invokes the other pod of the same service?

**Comment by LucaPetrucci** [comment]
Thank you for your comment.
This is an example of trace-driven benchmark see [trace-driven-benchmarks](https://github.com/mSvcBench/muBench/blob/main/Docs/Manual.md#trace-driven-benchmarks) in the documentation, these are only supported for REST request method.
Yes, the number after the escape string ”__ “ is randomly generated to allow a service to call itself (which happens in Alibaba's tracks). 
 
Since we are in the trace-driven case, when a service calls an external service it executes a POST request including a reduced trace in the body. To better explain it, if we refer to your example, the service s18 (in the trace “s18__58478”), which is a Pod in the Kubernetes cluster, executes a POST request to s18, itself, sending the subset of the trace which is the _“value”_ referred with its ID (“s18__58478”): 
```json
{
   "s18__60776":[
      {
         "s2__55751":[
            {
               
            }
         ]
      }
   ]
}
```
This is a new request to the s18 service ("s18__60776") handled like all others requests (execute his internal service and, in this example, do the request to the s2 service).

**Comment by kapilagrawal95** [comment]
So when a service calls itself, it will not use an RPC type request? Because in order for RPC to be used there have to be two cluster-wide reachable services. Is my understanding correct? Can you also tell me whether a service uses MQ to communicate with itself?

**Comment by LucaPetrucci** [comment]
For now, in µBench, it is only possible to specify two options for the request method ("rest" or "grpc"). The variable `request_method` in the configuration file WorkModelParameters.json defines this.
```bash
    "request_method":{
       "type": "metadata",
       "value":"rest"
    }
```
If you want to use _trace-driven benchmarks_ (as in the example), the only option is to specify "rest" as the request_method value.
No services do not use MQ to communicate.
When introducing trace-driven benchmarks, we focused on `rest` request methods, so we did not implement them for the `grpc` request methods. In any case, I think there is no problem opening a `grpc` channel with itself, so I think it is possible to add support for _trace-driven benchmarking_ in the case of the `grpc` request method.

**Comment by kapilagrawal95** [comment]
Thanks got it!

Just a minor thing: I was analyzing the "/par" directory in Alibaba example and found that for at least one app, "app2", there was no instance of "s25" in any of the traces even when the service_mesh.json file declares "s25". Just wanted to point out this caveat if this is unusual.

**Comment by LucaPetrucci** [comment]
Yes, that's right. This is probably due to the sanitisation of the traces, the service was left disconnected and therefore removed.

**Comment by kapilagrawal95** [comment]
Hi,

A follow up question: I was going through Alibaba's Matlab scripts. More specifically "trace_sanity.m". I see that you have hardcoded a variable "entry_id". According to the description, "entry_service_id: dm microservice id called by the user, this value is specified below". What does this mean? Are you looking at traces that correspond to users? If yes, how do you infer this user's guid?

**Comment by kapilagrawal95** [comment]
I am also interested in finding out the frequency at which a trace is seen in this data log. Are you recording this frequency of call graphs somewhere that I can use for these apps 2:29?
