### ISSUE TITLE
502 bad-gateaway in demo 

### ISSUE THREAD

**Issue by InvincibleWza1999** [mSvcBench/muBench#7]
Thank you for your execellent work and paper! However, i am currently facing some problems during my first deployment:
I deployed correctly according to the manual and deployed the demo application with 10 pods :
![image](https://user-images.githubusercontent.com/101389188/228568791-8580b853-532b-4bb4-8f07-8ae55ac8d1d9.png)
Howerver, when running the Runner code, the requests are often pending with high lantency:
![image](https://user-images.githubusercontent.com/101389188/228569147-c5089636-172c-466e-aa90-6e4399696e4f.png)
and when I tried to get access to the nginx NodePort, it shows 502 bad gateaway:
![image](https://user-images.githubusercontent.com/101389188/228569719-612c9559-b48a-40ac-8886-da71638fa53d.png)
Is there any mistake that i may encounter during my deployment? Appreciate your future answer sincerely.

**Comment by LucaPetrucci** [comment]
Thank you. 
I think you should have added the service to your request path.
The nginx pod is configured as a proxy that forwards the requests to the services.
This is the format to ask for a specific service:
```bash
http://MASTER_IP:GW-NGINX_NodePort/service
```
For example:
```
http://master:31113/s3
```
About the problem of the pending request, have you checked the stats (CPU, memory) of your cluster? Probably the workload is too high.

**Comment by InvincibleWza1999** [comment]
> 

I am trying to fix this according to your answer.  Thank you for your reply.

**Comment by InvincibleWza1999** [comment]
The services of s0-s9 are working properly I think, and Prometheus can detect the change of metrics in each pod when Runner.py is sending requests, but Jaeger can not  detect any trace, which is necessary in my experiment scenario. I deployed jaeger with Istio using the all-in-one mode. Could you provide me with any possible solutions? Thank you for your kind help.

**Comment by InvincibleWza1999** [comment]
> Thank you. I think you should have added the service to your request path. The nginx pod is configured as a proxy that forwards the requests to the services. This is the format to ask for a specific service:
> 
> ```shell
> http://MASTER_IP:GW-NGINX_NodePort/service
> ```
> 
> For example:
> 
> ```
> http://master:31113/s3
> ```
> 
> About the problem of the pending request, have you checked the stats (CPU, memory) of your cluster? Probably the workload is too high.
The services of s0-s9 are working properly I think, and Prometheus can detect the change of metrics in each pod when Runner.py is sending requests, but Jaeger can not detect any trace, which is necessary in my experiment scenario. I deployed jaeger with Istio using the all-in-one mode. Could you provide me with any possible solutions? Thank you for your kind help.

**Comment by InvincibleWza1999** [comment]
The services of s0-s9 are working properly I think, and Prometheus can detect the change of metrics in each pod when Runner.py is sending requests, but **Jaeger** can not detect any trace, which is necessary in my experiment scenario. I deployed jaeger with Istio using the all-in-one mode. Could you provide me with any possible solutions? Thank you for your kind help.

**Comment by LucaPetrucci** [comment]
Probably some misconfiguration that does not allow communication between Prometheus and Jaeger. Did you follow the [guide](https://github.com/mSvcBench/muBench/blob/main/Monitoring/kubernetes-full-monitoring/README.md)?

**Comment by InvincibleWza1999** [comment]
> Probably some misconfiguration that does not allow communication between Prometheus and Jaeger. Did you follow the [guide](https://github.com/mSvcBench/muBench/blob/main/Monitoring/kubernetes-full-monitoring/README.md)?

Thank you for your help, the trace now can be detected by **Jaeger**. However, after the execution of Runner.py which sends 2,000 requests to s0 successfully, I find that the memory usage of pods s0-s9 will not decrease, while their cpu usage will return normal:
![image](https://user-images.githubusercontent.com/101389188/230399008-9af27161-69d9-47b3-9776-dc2e7aa2e843.png)
![image](https://user-images.githubusercontent.com/101389188/230399164-fa5dcffe-c928-40ea-ba4e-3e206940e6db.png)
here memory_rss is gauge-type metric which can decrese, and cpu_usage is counter-type metric which can not decrease.
The internal service of each pod uses the default function which I do not modify.  Should I change the function, or did I conduct any misconfiguration? Thank you for your reply.

**Comment by andreadetti** [comment]
stale issue
