### ISSUE TITLE
Error when running Alibaba script: Unrecognized function or variable 'prettyjson'.

### ISSUE THREAD

**Issue by kapilagrawal95** [mSvcBench/muBench#9]
I ran into this error when executing the script "create_app_traces_for_mbench.m". I believe it is a minor library import for pretty json. On googling I found this repo: https://www.mathworks.com/matlabcentral/fileexchange/72667-prettyjson-m

Is this the prettyjson.m file that I should save in my current working directory so it gets picked up? Or is there an official Matlab package for this?

**Comment by andreadetti** [comment]
yes
